import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import { Header } from "./layout/Header/Header";
import { Sidebar } from "./layout/Sidebar/Sidebar";
import { Footer } from "./layout/Footer/Footer";
import s from "./layout.module.css";
import cn from "classnames";
import { AppContextProvider, IAppContext } from "./context/app.context";
import { getMenu } from "./api/menu-api";

const inter = Noto_Sans_KR({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Our the best choice",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const menu = await getMenu(0);
  const firstCategory = 0;

  return (
    <html lang="en">
      <body className={cn(inter.className, s.wrapper)} suppressHydrationWarning={true}>
        <AppContextProvider menu={menu} firstCategory={firstCategory}>
          <Header className={s.header} />
          <Sidebar className={s.sidebar} />
          <main className={s.main}>{children}</main>
          <Footer className={s.footer} />
        </AppContextProvider>
      </body>
    </html>
  );
}
